name = "workflow-cron"
type = "webpack"
account_id = "fb1f542488f2441acf88ca15f3a8390d"
workers_dev = true
webpack_config = "webpack.config.js"
kv_namespaces = [
    { binding = "WORKFLOW_CRON_LAST_RUNS", id = "4fc9f04e2f29425c878cf74200359002", preview_id = "4fc9f04e2f29425c878cf74200359002" }
]

[triggers]
crons = ["* * * * *"]

[env.production]
kv_namespaces = [
    { binding = "WORKFLOW_CRON_LAST_RUNS", id = "361eeb4aad3f4fc592c5855dd35d7f71" }
]
